# Generated by Django 4.2.30 on 2026-04-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicproject',
            old_name='name',
            new_name='title',
        ),
    ]
